//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.OperacionesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperacionesService.IOperaciones")]
    public interface IOperaciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/DoWork", ReplyAction="http://tempuri.org/IOperaciones/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/DoWork", ReplyAction="http://tempuri.org/IOperaciones/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Saludar", ReplyAction="http://tempuri.org/IOperaciones/SaludarResponse")]
        string Saludar(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Saludar", ReplyAction="http://tempuri.org/IOperaciones/SaludarResponse")]
        System.Threading.Tasks.Task<string> SaludarAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Suma", ReplyAction="http://tempuri.org/IOperaciones/SumaResponse")]
        int Suma(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Suma", ReplyAction="http://tempuri.org/IOperaciones/SumaResponse")]
        System.Threading.Tasks.Task<int> SumaAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Resta", ReplyAction="http://tempuri.org/IOperaciones/RestaResponse")]
        int Resta(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Resta", ReplyAction="http://tempuri.org/IOperaciones/RestaResponse")]
        System.Threading.Tasks.Task<int> RestaAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Multiplicación", ReplyAction="http://tempuri.org/IOperaciones/MultiplicaciónResponse")]
        int Multiplicación(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Multiplicación", ReplyAction="http://tempuri.org/IOperaciones/MultiplicaciónResponse")]
        System.Threading.Tasks.Task<int> MultiplicaciónAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/División", ReplyAction="http://tempuri.org/IOperaciones/DivisiónResponse")]
        int División(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/División", ReplyAction="http://tempuri.org/IOperaciones/DivisiónResponse")]
        System.Threading.Tasks.Task<int> DivisiónAsync(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperacionesChannel : PL.OperacionesService.IOperaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperacionesClient : System.ServiceModel.ClientBase<PL.OperacionesService.IOperaciones>, PL.OperacionesService.IOperaciones {
        
        public OperacionesClient() {
        }
        
        public OperacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string Saludar(string nombre) {
            return base.Channel.Saludar(nombre);
        }
        
        public System.Threading.Tasks.Task<string> SaludarAsync(string nombre) {
            return base.Channel.SaludarAsync(nombre);
        }
        
        public int Suma(int x, int y) {
            return base.Channel.Suma(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SumaAsync(int x, int y) {
            return base.Channel.SumaAsync(x, y);
        }
        
        public int Resta(int x, int y) {
            return base.Channel.Resta(x, y);
        }
        
        public System.Threading.Tasks.Task<int> RestaAsync(int x, int y) {
            return base.Channel.RestaAsync(x, y);
        }
        
        public int Multiplicación(int x, int y) {
            return base.Channel.Multiplicación(x, y);
        }
        
        public System.Threading.Tasks.Task<int> MultiplicaciónAsync(int x, int y) {
            return base.Channel.MultiplicaciónAsync(x, y);
        }
        
        public int División(int x, int y) {
            return base.Channel.División(x, y);
        }
        
        public System.Threading.Tasks.Task<int> DivisiónAsync(int x, int y) {
            return base.Channel.DivisiónAsync(x, y);
        }
    }
}
